In [34]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go

In [38]:
df = pd.read_csv("../data/processed/games_march2025_cleaned.csv")
df = df.sort_values(by="recommendations", ascending=False)
df.head(1)

,appid,name,release_date,required_age,price,dlc_count,header_image,windows,mac,linux,...,publishers,positive,negative,average_playtime_forever,median_playtime_forever,discount,peak_ccu,pct_pos_total,num_reviews_total,tags_sep
0,2358720,Black Myth: Wukong,2024-08-19,13.0,59.99,2,https://shared.akamai.steamstatic.com/store_it...,True,False,False,...,['Game Science'],1098373,37811,0,0,0,35990,96.0,825621.0,"['Mythology', 'Action RPG', 'Action', 'Souls-l..."

### Quanto o 1° se diferencia dos demais em preço?

In [16]:
prices = df[:10].price.values
prices

array([59.99, 39.99, 19.99, 29.99, 39.99, 38.99, 29.99,  4.49, 34.99,
       34.99])

In [31]:
idx_to_compare = 0
prices_sem_itc = np.delete(prices, idx_to_compare)

In [32]:
np.average(prices_sem_itc)

30.37888888888889

In [33]:
prices[idx_to_compare] / np.average(prices_sem_itc) # quase o dobro da média

1.974726601075308

In [29]:
idx_to_compare = 4
prices_sem_itc = np.delete(prices, idx_to_compare)
prices[idx_to_compare] / np.average(prices_sem_itc) # menor, mais ainda mais que a média

1.2266453086125215

In [30]:
idx_to_compare = -3
prices_sem_itc = np.delete(prices, idx_to_compare)
prices[idx_to_compare] / np.average(prices_sem_itc) # bem abaixo da média

0.12286035693654798

In [45]:
idx_to_compare = 0
colors = ['crimson' if i == idx_to_compare else 'lightblue' for i in range(len(prices))]
media_sem_idx0 = np.mean(np.delete(prices, idx_to_compare))
fig_jogo_preco = go.Figure()

fig_jogo_preco.add_trace(go.Bar(
    x=[i for i in df[:10].name.values],
    y=prices,
    marker_color=colors,
    text=[f"{p:.2f}" for p in prices],
    textposition="outside",
    name="Jogo Destacado"
))

fig_jogo_preco.add_trace(go.Scatter(
    x=[i for i in df[:10].name.values],
    y=[media_sem_idx0]*len(prices),
    mode='lines',
    line=dict(color='green', dash='dash'),
    name=f'Média (sem o {idx_to_compare+1}º jogo)'
))

fig_jogo_preco.update_layout(
    title=f'Gráfico de Preços com Destaque no {idx_to_compare+1}º Jogo',
    xaxis_title='Jogo',
    yaxis_title='Preço ($)',
    showlegend=True,
    bargap=0.2,
    template='plotly_white'
)

fig_jogo_preco.show()

### Quanto tempo a mais de jogo?

In [69]:
top10.head(1)

,appid,name,release_date,required_age,price,dlc_count,header_image,windows,mac,linux,...,publishers,positive,negative,average_playtime_forever,median_playtime_forever,discount,peak_ccu,pct_pos_total,num_reviews_total,tags_sep
0,2358720,Black Myth: Wukong,2024-08-19,13.0,59.99,2,https://shared.akamai.steamstatic.com/store_it...,True,False,False,...,['Game Science'],1098373,37811,0,0,0,35990,96.0,825621.0,"['Mythology', 'Action RPG', 'Action', 'Souls-l..."

In [58]:
top10 = df[:10]
x = top10.recommendations.values
y = top10.peak_ccu.values
names = top10.name.values

In [65]:
idx_to_compare = 0
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=x,
    y=y,
    mode='markers',
    marker=dict(size=10, color='lightblue'),
    text=names
))

fig.add_trace(go.Scatter(
    x=[x[idx_to_compare]],
    y=[y[idx_to_compare]],
    mode='markers+text',
    marker=dict(size=14, color='crimson', symbol='circle'),
    textposition='top center',
    text=names[idx_to_compare]
))

fig.update_layout(
    title='Relação atividade x recomendações',
    xaxis_title='Recommendations',
    yaxis_title='Peak_ccu',
    template='plotly_white'
)

fig.show()